import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Packer,
} from 'docx'
import { saveAs } from 'file-saver'

/**
 * Parse markdown PRD into simple blocks for DOCX conversion.
 * Handles: ## headings, > blockquotes, - bullets, and body paragraphs.
 */
function parseMarkdownBlocks(md: string) {
  const lines = md.split('\n')
  const blocks: { type: 'heading' | 'quote' | 'bullet' | 'paragraph'; text: string }[] = []

  for (const raw of lines) {
    const line = raw.trimEnd()
    if (!line) continue

    if (line.startsWith('## ')) {
      blocks.push({ type: 'heading', text: line.replace(/^##\s+/, '') })
    } else if (line.startsWith('# ')) {
      blocks.push({ type: 'heading', text: line.replace(/^#\s+/, '') })
    } else if (line.startsWith('> ')) {
      blocks.push({ type: 'quote', text: line.replace(/^>\s*/, '') })
    } else if (/^[-*]\s/.test(line)) {
      blocks.push({ type: 'bullet', text: line.replace(/^[-*]\s+/, '') })
    } else {
      blocks.push({ type: 'paragraph', text: line })
    }
  }

  return blocks
}

/** Strip basic markdown inline formatting for plain-text runs. */
function stripInline(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/__(.+?)__/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/_(.+?)_/g, '$1')
    .replace(/`(.+?)`/g, '$1')
}

/** Build an array of TextRun from a line, preserving **bold** segments. */
function buildRuns(text: string, base?: Partial<{ italics: boolean; color: string; size: number }>): TextRun[] {
  const runs: TextRun[] = []
  const parts = text.split(/(\*\*.*?\*\*)/g)
  for (const part of parts) {
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true, font: 'Helvetica', size: base?.size ?? 22, ...base }))
    } else if (part) {
      runs.push(new TextRun({ text: part, font: 'Helvetica', size: base?.size ?? 22, ...base }))
    }
  }
  return runs
}

export async function exportPrdToDocx(markdown: string, title: string) {
  const blocks = parseMarkdownBlocks(markdown)

  const children: Paragraph[] = [
    // Title
    new Paragraph({
      children: [new TextRun({ text: title, bold: true, font: 'Helvetica', size: 32 })],
      spacing: { after: 300 },
      alignment: AlignmentType.LEFT,
    }),
    // Subtitle
    new Paragraph({
      children: [
        new TextRun({
          text: `Product Requirements Document — Generated by SignalPath`,
          font: 'Helvetica',
          size: 20,
          color: '666666',
        }),
      ],
      spacing: { after: 400 },
    }),
  ]

  for (const block of blocks) {
    switch (block.type) {
      case 'heading':
        children.push(
          new Paragraph({
            children: [new TextRun({ text: block.text, bold: true, font: 'Helvetica', size: 26 })],
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 300, after: 120 },
          }),
        )
        break
      case 'quote':
        children.push(
          new Paragraph({
            children: buildRuns(block.text, { italics: true, color: '555555' }),
            indent: { left: 720 },
            spacing: { before: 80, after: 80 },
          }),
        )
        break
      case 'bullet':
        children.push(
          new Paragraph({
            children: buildRuns(block.text),
            bullet: { level: 0 },
            spacing: { before: 40, after: 40 },
          }),
        )
        break
      default:
        children.push(
          new Paragraph({
            children: buildRuns(block.text),
            spacing: { before: 60, after: 60 },
          }),
        )
    }
  }

  const doc = new Document({
    sections: [{ children }],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${stripInline(title).replace(/[^a-zA-Z0-9 ]/g, '').trim().replace(/\s+/g, '_')}_PRD.docx`)
}

export function printPrdAsPdf() {
  window.print()
}
